# Python 기초 문법

### 주요 내용

1. 파이썬의 기본 정의와 데이터 타입에 대한 이해
2. 파이썬 기본 제어문에 대한 이해
3. 파이썬 기본 데이터구조에 대한 이해

<br>

### 목표 
1. 파이썬의 기본 정의인 클래스, 함수, 변수를 이해하고 데이터타입에 대하여 배운다. 
2. if 문을 활용한 조건, for문 또는 While문을 활용한 반복 작업을 구현 한다.
3. 리스트와 튜플, 딕셔너리 등의 기본 내장 데이터구조를 활용하여 여러개의 데이터를 저장하고 활용 한다.
4. 외부 라이브러리로 제공되는 데이터구조를 활용해 본다.


<br>
<hr>
<br>



<br>

## 1. 형식의 이해



<br>



### 1.1. 변수 할당

변수에 데이터를 할당하므로 데이터를 지속 보관할 수 있음

In [1]:
# 할당(assign), 저장의 의미를 가짐
#     적절한 표현의 변수이름을 지정하고 = 을 활용하여 할당
num = 10
num

10

In [2]:
# 이미 할당된 변수에 = 을 사용하면 재할당이 이루어짐
num = 10
num = 11
num

11

In [3]:
# 변수에 할당이 이루어진 또다른 변수 할당 가능
#     print()를 활용하여 데이터를 터미털(또는 셸)에 출력 가능
num1 = 10
num2 = num1
print(num1)
print(num2)

10
10


In [4]:
# 할당은 참조의 개념임을 유의할 것
num1 = 10
num2 = num1
num1 = 11
print(num1)
print(num2)

11
10


In [5]:
# 변수가 할당 받을수 있는것은 객체, 파이썬은 모든 데이터가 객체로 이루어져 있음
num = 1
name = '삼성'
# company = Samsung()


<br>
<br>

### 1.2. 기본 데이터 타입(type, 형식)

파이썬에서 데이터는 모두 객체로 이루어져 있어 객체에 따른 **타입(type)** 을가짐
파이썬은 다음과 같이 기본적인 자료형 데이터를 객체로 제공

* int : 정수(integer)
* str : 문자열(string)
* float : 소수점, 비율을 포함한 실수


In [6]:
# 정수형 타입
#     type() 을 활용하여 데이터의 타입 확인 가능
num = 10
type(num)

int

In [7]:
# 실수형 타입
num = 10.1
type(num)

float

In [8]:
# 정수형 간의 연산자 활용
#     숫자형 사칙연산 +, -, *, /, //, %, **
num1 = 10
num2 = 20
num1 + num2

30

In [9]:
# 실수형 혼합 연산
num1 = 10
num2 = 10.1
num1 + num2

20.1

In [10]:
# 나누기 연산시 실수형으로 변환
num1 = 10
num2 = 20
num2 / num1

2.0

In [11]:
# += 을 활용하여 누적 연산 가능
num = 10
num += 10 # num = num + 10
num

20

In [12]:
# 문자열 타입 
#     파이썬은 단일 문자타입 대신 문자열 타입만 존재
#     '', "" 둘다 사용가능
name1 = '삼성'
name2 = "전자"
print(type(name1))
print(type(name2))

<class 'str'>
<class 'str'>


In [13]:
# 문자열 간의 연산 활용
#     문자열간 연산은 숫자형과 다르게 적용
name1 = '삼성'
name2 = '전자'
name1 + name2

'삼성전자'

In [14]:
# 문자열과 숫자형 연산 가능
name = '삼성'
num = 3
name * num

'삼성삼성삼성'

In [15]:
# 문자열의 포맷 방법
#     다양한 변수를 하나의 문자열로 생성   
#     ''.format() 또는 f''를 이용

num = 1
name = '데이터분석'

print('{}일차 {} 수업에 오신걸 환영합니다'.format(num, name))
print(f'{num}일차 {name} 수업에 오신걸 환영합니다')

1일차 데이터분석 수업에 오신걸 환영합니다
1일차 데이터분석 수업에 오신걸 환영합니다


In [16]:
# bool 타입
#     True와 False로 표현됨
#     False는 0, True는 0이외의 값으로 표현
t = True
f = False
type(t)

bool

In [17]:
# 비교연산자의 활용
num1 = 100
num2 = 10

print(num1 == num2)
print(num1 != num2)
print(num1 > num2)
print(num1 <= num2)


False
True
True
False


In [18]:
# 논리 연산 활용
print(not True)
print(True and True)
print(True and False)
print(True or False)
print(False or False)

False
True
False
True
False


In [19]:
# 데이터 타입 변환 (형변환)
#     파이썬에서 int(),float(),str()등 내장함수로 제공 
num1 = int(10.1)
num2 = float(10)
num3 = int('10')
num4 = str(10)
print(num1, num2, num3, num4)
print(type(num1), type(num2), type(num3), type(num4))

10 10.0 10 10
<class 'int'> <class 'float'> <class 'int'> <class 'str'>


#### [실습] x에 10.1을 저장하고, y에 101을 저장한 다음 더한후 정수로 출력

#### [실습] a=1, b=5로 할당하고 문자열 포맷으로 'a + b는'과 a+b 계산 결과를 print( )로 함께 출력

출력 결과 예시  
`1 + 5는 6`

#### [심화] 초를 나타내는 time 값을 다음과 같이 시간,분,초로 나타내는 포맷으로 변경하세요

`5000초는 1시간 23분 20초 입니다.`

In [20]:
time = 5000

### 1.3. 객체와 함수
- 함수는 일시적인 기능을 수행 (일회성 데이터)
- 객체는 지속적인 구조체를 이루기위해 존재 (지속적 데이터)

#### def을 통해 특정 기능을 수행하는 함수 정의

    def 함수이름(인자1,인자2):
        return 반환
    
- **인자** : 함수 실행시 필요한 입력 데이터(input) 
- **반환** : 함수 실행후 결과로 제공될 출력 데이터(output)

In [21]:
# def 을 통한 함수 정의
#     파이썬은 TAB(들여쓰기)기준으로 코드 실행영역을 지정


def concat(arg1, arg2, arg3=10): # 함수이름은 모두 소문자 단어구분 _
    cat = arg1 + arg2 + arg3
    return cat

# 함수 이름을 통한 함수 실행(사용)
out1 = concat(10, 20)
print(out1)
out2 = concat(10, 20, arg3=30)
print(out2)

40
60


In [22]:
# 함수 내부의 변수는 외부에서 접근 불가(return 제외)
#     인자(parameter)와 반환(return)적절히 활용 
    
def fun1():
    data1 = 100

fun1()
print(data1)

NameError: name 'data1' is not defined

#### [실습] 다음 변수 inp로 부터 두 함수를 사용하여 최종 출력이 30이 되게 하세요 


In [23]:
def multen(x):
    return x *10

def plu(x,y=0):
    return x+y

In [24]:
inp = 2


#### 실제 객체는 class라는 명령어로 정의

    class 객체이름:
        self.변수 및 메소드

- **클래스** : 각종 데이터와 기능을 내포시킨 객체의 정의(코드상태)
- **인스턴스** : 정의상태인 클래스가 실행되어 실질적으로 존재하는 상태(지속데이터)

In [25]:
# class를 통해 객체 정의 

class Samsung: #클래스 이름은 맨앞글자 대문자 단어구분 대문자
    
    def __init__(self, name): # 생성자 메소드 클래스->인스턴스 과정에 실행되는 함수
        self.name = name # self.name 변수와 name 지역변수는 다른 변수
    
    def get_name(self): # 메소드 정의 인스턴스 상태일때 .으로 사용 
        return self.name


#### 정의된 클래스를 실행하여 변수에 할당하면 **인스턴스**
- 인스턴스의 데이터타입은 클래스의 이름
- 인스턴스에서 .(도트연산)을 통해 클래스에서 정의된 메소드, self변수 사용

In [26]:
# 클래스 이름을 호출하여 실행, 변수에 할당하여 인스턴스화


company = Samsung('삼성') # 클래스 실행 인자는 __init__ 함수의 인자
print(type(company))
name = company.get_name() # 인스턴스 변수에서 .(도트연산) 활용
print(name)

<class '__main__.Samsung'>
삼성


#### [실습] 다음 클래스(Member)를 활용해 자신의 이름과 나이가 들어간 인스턴스 생성하고, print_info() 함수를 통해 다음 문구 출력

`저의 이름은 000, 나이는 00 입니다.`

In [27]:
class Member:
    def __init__(self, name, age):
        self.name = name
        self.age = age 
        
    def print_info(self):
        return f'저의 이름은 {self.name} 나이는 {self.age} 입니다.'

#### [심화] 다음 코드실행시 결과가 20이 나올수 있게 Myclass를 정의하세요

In [28]:
myclass = Myclass(15)
myclass.add_num(5)
myclass.get_num()

NameError: name 'Myclass' is not defined

<br>

## 2. 흐름 제어문의 활용

### 2.1. if 조건문  

**if** 명령어 옆에 오는 bool 데이터를 체크하여 코드 실행여부 판단  
**else**나  **elif**를 추가로 활용 가능  


In [29]:
# if의 활용
score=10

if score >=80:
    print('합격') # True인 경우 실행

In [30]:
# if와 else의 활용
score=10

if score >=80:
    print('합격') # True인 경우 실행
else:
    print('탈락') # False인 경우 실행

탈락


In [31]:
# if와 elif와 else의 활용

score = None # 결측 (데이타 없음을 의미)

if score is None: # is : 타입까지 동일해야 True
    print('미응시')
else:
    if score >=80:
        print('합격')
    else:
        print('탈락')

if score is None:
    print('미응시')
elif score >=80:
    print('합격')
else:
    print('탈락')

미응시
미응시


<br>

### 2.2. for 반복문
**for**는 반복 대상을 지정하고 특정한 명령을 반복 실행

    for 변수 in 이터러블:
        반복코드
     
- **이터러블**: 여러개의 데이터를 가지고있으며, 데이터를 순서대로 출력가능한 구조

In [32]:
# range(s, e): s값부터 e-1값까지의 수열을 만드는 함수

for i in range(0,5):
    print(f'{i}번째 반복')

0번째 반복
1번째 반복
2번째 반복
3번째 반복
4번째 반복


In [33]:
count = 0

for i in [0,1,2,3,4]:
    count += i ## 반복할 때마다 i를 더함   
    print(f'{i}번째 값은 {count}')

0번째 값은 0
1번째 값은 1
2번째 값은 3
3번째 값은 6
4번째 값은 10


`break` : 포함된 반복문을 중단시킴  
`continue` : 이후 반복문 내의 코드를 실행하지 않고 다음 반복으로 넘김

In [34]:
# for문 안에서 if문을 활용

for a in range(1,10):
    if a % 3 == 0: # 3로 나눈 나머지가 0이면
        continue
    if a % 5 == 0:
        break
    print(a)

1
2
4


if 문에서 in 연산 활용시 특정 값이 이터러블내에 포함되어있으면 True

In [35]:
# if 데이터 in 이터러블

if 0 in [1,2,3,4]:
    print('zero in')

if 1 in [1,2,3,4]:
    print('one in')

one in


<br>

#### [실습] 구구단 19단 출력하기  
`19 X 1 = 19`  
`19 X 2 = 38 ... ` 


In [36]:
#1. 참고
print(f'{19} X {1} = {19}')

19 X 1 = 19


#### [실습] 아래의 숫자 리스트 *x* 에서 10 이상인 숫자만 따로 모아 합계 계산하기

In [37]:
#2. 
nums = [9, 10, 4, 22, 3, 19]

#### [심화] 다음 리스트를 순서대로 출력하세요. 단 *가 나오면 이전 숫자들의 합으로 출력하고 - 가 나오면 반복을 중지

    출력결과
    1
    2
    3
    4
    5
    15
    7

In [38]:
nums2 = [1, 2, '*', 4, 5, '*', 7, '-', 9]


<br>

## 3. 여러 값을 묶은 데이터구조

`1`, `'삼성'`처럼 하나의 값이 아니라 여러개의 값을 특정 구조로 저장

- 리스트(list)
- 튜플(tuple), 문자열(str)
- 사전(dictionary)

순서(인덱스가)가 있는 데이터구조는 **이터러블**

### 3.1. 가변 시퀀스 리스트

- 가변 시퀀스형으로 내부값을 자유롭게 바꿀수 있음
- 내부를 변형해주는 다양한 메소드 포함
- 순서(인덱스) 기반으로 데이터를 저장하고 찾아옴

#### 리스트 생성 과 표현
> 리스는 []로 표현

In [39]:
# 비어있는 리스트 생성
empty = [] 
print(empty)

# 데이터를 넣어 리스트 생성
salary = [5000, 6000, 7000, 6000, 9000]
print(salary)

[]
[5000, 6000, 7000, 6000, 9000]


In [40]:
# 다양한 타입이 들어올 수 있음
jobs = ['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']
print(jobs)
sample = ['회로설계', 5000, '반도체공정설계', 6000, 'S/W개발', 7000]
print(sample)

['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']
['회로설계', 5000, '반도체공정설계', 6000, 'S/W개발', 7000]


In [41]:
# for문과 if문을 활용한 리스트생성 (컴프리헨션)
seq_num = [x for x in range(1,10)]
print(seq_num)

seven_mul = [x for x in range(1,101) if x%7==0]
print(seven_mul)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


In [42]:
# list() 함수 활용하여 생성 (형변환)
empty = list() # empty = []
print(empty)
seq = list(range(1, 20))
print(seq)

[]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]



#### 리스트의 주요 메서드
> append(x): x를 맨뒤에 추가  
> extend(x) : x를 이어 붙이기(구조내 요소를 추가)  
> sort() : 내부 요소를 정렬  
> reverse() : 내부 요소를 반대로 구성  

In [43]:
# append : 리스트 맨뒤에 항목 추가하기

salary = [5000, 6000, 7000, 6000, 9000]
salary.append(10000)
salary

[5000, 6000, 7000, 6000, 9000, 10000]

In [44]:
# extend : 또다른 리스트를 이어 붙이기(구조내 요소를 추가)
# + 연산을 활용하여 이어 붙이기 가능

salary = [5000, 6000, 7000, 6000, 9000]
salary.append([6000, 5000])
print(salary)

salary = [5000, 6000, 7000, 6000, 9000]
salary.extend([6000, 5000])
print(salary)

concat = [5000, 6000, 7000, 6000, 9000] + [6000, 5000]
print(concat)

[5000, 6000, 7000, 6000, 9000, [6000, 5000]]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]


In [45]:
# sort : 내부 요소를 정렬
# reverse : 내부 요소를 반대로 구성

salary = [9000, 5000, 6000, 7000, 6000]
salary.sort()
print(salary)

salary = [9000, 5000, 6000, 7000, 6000]
salary.reverse()
print(salary)

[5000, 6000, 6000, 7000, 9000]
[6000, 7000, 6000, 5000, 9000]



#### [실습] 점심/저녁 메뉴 3개를 리스트로 묶어 menu로 저장하기 


#### [실습] menu 리스트에서 append( )로 메뉴 하나 더 추가하기



#### [실습] 다음 두 리스트를 이어붙이고 이름 순으로 정렬하여 출력하기

#### [심화] 리스트를 이어붙일때 3가지 다른 방법을 이용해 결과 출력하기

In [46]:
list1 = ['a','f','c']
list2 = ['b','e']


<br>

### 3.2. 시퀀스 연산 활용  

- `변수[]`: 구조내에 저장되어 있는 특정 데이터에 접근 
- `len(), max(), sum()`: 구조의 길이, 최대값, 총합을 반환
- `for in`: 구조내의 모든 데이터에 접근(탐색)
- `if in`: 구조내의 모든 데이터와 비교(포함) 

#### 리스트에서 시퀀스 연산 []에 index(순서) 를 넣어 원하는 데이터에 접근

In [47]:
# [index]를 활용한 데이터 선택
#     index는 0부터 시작 : 첫번째 값이 0
salary = [5000, 6000, 7000, 6000, 9000]
print(salary[0])
print(salary[2])

5000
7000


In [48]:
# [start:end]을 활용해 범위 지정 가능(슬라이싱), 끝 인덱스 미포함
salary = [5000, 6000, 7000, 6000, 9000]
print(salary[:3])
print(salary[2:4])

[5000, 6000, 7000]
[7000, 6000]


In [49]:
# 음수 인덱스로 뒤에순서를 지정 가능
salary = [5000, 6000, 7000, 6000, 9000]
print(salary[-1])
print(salary[-3:])

9000
[7000, 6000, 9000]


In [50]:
# 인덱스를 활용한 업데이트
salary[3] = 60000
salary

[5000, 6000, 7000, 60000, 9000]

In [51]:
# 인덱스가 없으면 에러
salary[6] = 60000

IndexError: list assignment index out of range

In [52]:
# 인덱스에 접근하여 삭제
del salary[3]
salary

[5000, 6000, 7000, 9000]

In [53]:
# 반복문을 활용하여 리스트 탐색
for data in salary:
    print(data) 

5000
6000
7000
9000


#### [실습] menu에서 첫번째 메뉴만 선택하여 출력

#### [실습] menu에서 세번째~마지막 메뉴를 한번에 선택하여 출력

#### [실습] menu에서 세번째 메뉴를 '우동'으로 변경

#### [실습] for 문을 활용하여 최종 menu데이터를 전부 출력(print)


In [54]:
menu = ['돈까스', '삼겹살', '치킨', '불고기']

<br>

### 3.3. 불변 시퀀스 튜플(tuple)과 문자열(str)
튜블과 문자열은 내부적으로 구조를 바꿀수 없는 불변 시퀀스형

<br>

#### 튜플 생성 및 표현
> 튜플은 ()를 활용해서 만들 수 있고, 소괄호는 생략 가능



In [55]:
aa = (1, 2, 3)
bb = '아침', '점심', '저녁'

print(aa)
print(bb)

(1, 2, 3)
('아침', '점심', '저녁')


In [56]:
# 인덱스 활용하여 시퀀스 연산 가능
print(aa[0])
print(bb[1:])

1
('점심', '저녁')


In [57]:
# 추가/업데이트 불가능, 내부 변환 메소드도 없음
aa[0] = 4

TypeError: 'tuple' object does not support item assignment

In [58]:
# 튜플 요소의 순서를 맞추어 변수 할당 가능

a, b = ('아침', '점심')
print(a)
print(b)

아침
점심


#### 문자열 데이터구조 활용
자료형에서 본 문자열은 실제 불변시퀀스의 데이터구조형태를 가짐, 불변시퀀스형이지만 다양한 메소드가 있음(복사 반환)
> replace(x,y) : x문자열을 y문자열로 대체  
> strip() : 앞뒤 공백 제거  
> split(x) : x문자열을 기준으로 분리하여 리스트생성  

In [59]:
# 인덱스 활용하여 시퀀스 연산 가능 (할당은 불가)
s = '파이썬 기초 데이터구조'
print(s[2])
print(s[4:6])

썬
기초


In [60]:
# replace() : 원하는 부분문자열을 다른 문자열로 대체
s = '파이썬 기초 데이터구조'
s1 = s.replace('기초', '심화')
s1

'파이썬 심화 데이터구조'

In [61]:
# strip() : 앞뒤 공백 제거
s = '   파이썬 기초 데이터구조  '
s = s.strip()
s

'파이썬 기초 데이터구조'

In [62]:
# split() : 원하는 문자열을 기준으로 분리하여 리스트생성
s = '파이썬 기초 데이터구조'
s = s.split(' ') # 공백(띄어쓰기) 기준으로 분리
s


['파이썬', '기초', '데이터구조']

#### [실습] 다음 문자열에서 stop_words에 해당하는 단어를 뺀 단어 리스트를 만들어 출력 

    출력 결과
    ['삼성', '빅데이터', '데이터분석', '파이썬', '시각화']

In [63]:
s2 = '  삼성 빅데이터 데이터분석 데이터구조 파이썬 시각화 판다스     '
stop_words = '데이터구조'

#### [심화] 

In [64]:
s2 = '  삼성 빅데이터 데이터분석 데이터구조 파이썬 시각화 판다스     '
stop_words = ['데이터구조', '판다스', '시각화']

### 3.4. 해쉬셋과  딕셔너리
순서가 아닌 해쉬를 기반으로 데이터를 구조적으로 저장

#### 해쉬셋 생성 과 표현
> 해쉬셋은 {}로 표현되며 해쉬특성으로 인해 내부 요소는 고유값을 가지고 순서가 없음

In [65]:
# 순서가 없는 해쉬셋
s = {'돈까스','치킨','덮밥'}
s.add('우동')
s

{'덮밥', '돈까스', '우동', '치킨'}

In [66]:
set(['돈까스','치킨','덮밥','덮밥'])

{'덮밥', '돈까스', '치킨'}

In [67]:
# 중복이 되지 않는 해쉬셋
s = {'돈까스','치킨','덮밥'}
s.add('덮밥')
s

{'덮밥', '돈까스', '치킨'}

#### 딕셔너리 생성 과 특징

- 딕셔너리는 *키(key)* 와 *값(value)* 을 mapping하여 여러 값을 구분해서 저장
- *key*는 해쉬특성을 가져 찾는 속도가 빠름
- 웹통신 데이터뭉치인 json형과 비슷한 구조로 많이 활용

> 해쉬셋과 동일한 {}로 만들어지며 요소가 단일값이 아닌 {key:value} 형태로 맵핑하여 생성 


In [68]:
# 이 강의의 속성을 딕셔너리로 저장
this_lecture = {'회사':'삼성전자', '분석도구':'Python', '기간':'3일'}
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '기간': '3일'}

In [69]:
# 키를 활용 시퀀스 연산자 활용
this_lecture['회사']

'삼성전자'

In [70]:
# 메서드 get()을 활용한 선택
this_lecture.get('회사1',0)

0

In [71]:
# 시퀀스 연산자에 새로운 키를 넣고 할당하여 키:값 추가
this_lecture['수강인원'] = 20
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '기간': '3일', '수강인원': 20}

In [72]:
# 시퀀스 연산자에 기존 키를 넣고 할당하여 값 변경
this_lecture['기간'] = '4일'
this_lecture


{'회사': '삼성전자', '분석도구': 'Python', '기간': '4일', '수강인원': 20}

In [73]:
# del 연산을 활용한 키:값 제거
del this_lecture['기간']
this_lecture

{'회사': '삼성전자', '분석도구': 'Python', '수강인원': 20}

In [74]:
# 키 목록 반환
this_lecture.keys()

dict_keys(['회사', '분석도구', '수강인원'])

In [75]:
# 리스트 형식으로 변환
list(this_lecture.keys())

['회사', '분석도구', '수강인원']

In [76]:
list(this_lecture)

['회사', '분석도구', '수강인원']

In [77]:
# 값 목록 반환
this_lecture.values()

dict_values(['삼성전자', 'Python', 20])

#### [실습] 각자 본인의 아래 정보를 딕셔너리로 저장

(딕셔너리의 값(value)에 리스트를 넣는 것도 가능)

* 이름
* 부서
* 연차
* 관심메뉴 3개(리스트로 구성)

#### [실습] 저장된 딕셔너리에서 관심메뉴의 2번째 메뉴 가져와 출력


In [78]:
my_info = {}

<br>

## 4. numpy와 DataFrame
파이썬 내장 데이터구조가 아닌 외부 라이브러리로 제공되는 대표적인 데이터구조



### 4.1 numpy를 활용한 배열
**numpy**는 **ndarray**라는 형식을 활용해서 다차원의 배열형식을 만들고 다양한 연산과 처리를 지원
- 배열은 리스트와 비슷하지만 구조적인 차이로 크기가 고정됨
- 배열은 여러개의 **축(axis)** 이 있는 다차원의 **형상(shape)** 을 가짐 

#### 배열생성 과 특징
> array()함수를 활용하여 배열생성, shape로 형상 출력가능

In [79]:
import numpy as np

In [80]:
x = [1, 2, 4, 8]
y = np.array(x)
print(y)
print(y.shape)

[1 2 4 8]
(4,)


##### 배열 형상 이해
<img src="./data/array1.png"  width = 640 ></img>

In [81]:
# 배열의 형상은 (0번축 크기, 1번축 크기, ...)로 표현됨

y2 = np.array([[1,2,3,4], 
               [9,8,7,6]])
y3 = np.array([[0, 1], 
               [1, 0]])

print(y2.shape)
print(y3.shape)

(2, 4)
(2, 2)


In [82]:
# 시퀀스 연산자 활용
print(y[:3])
print(y2[0,3])
print(y2[1,0:2])

[1 2 4]
4
[9 8]


In [83]:
y2[0,1] = 10
y2

array([[ 1, 10,  3,  4],
       [ 9,  8,  7,  6]])

In [84]:
y2[0] = [2,3,4,5]

In [85]:
# 일괄 산술 연산
y2 * 2 + 1

array([[ 5,  7,  9, 11],
       [19, 17, 15, 13]])

In [86]:
# 축을 설정하여 연산
y2 = np.array([[1,2,3,4], 
               [9,8,7,6]])

print(np.sum(y2, axis = 0))
print(np.sum(y2, axis = 1))

[10 10 10 10]
[10 30]


In [87]:
# 다양한 연산 함수 제공
print(np.sqrt(y)) # 제곱근
print(np.power(y, 2)) # 거듭제곱
print(np.log(y)) # 자연로그
print(np.exp(y)) # 지수

[1.         1.41421356 2.         2.82842712]
[ 1  4 16 64]
[0.         0.69314718 1.38629436 2.07944154]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


In [88]:
# 배열 형상 변환
np.reshape(y2, (4,2))

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

In [89]:
# 행렬 배열 역변환
np.transpose(y2)

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6]])

#### [실습] 다음 배열(arr)의 모양을 출력하고  0번축의 0 ~ 2번, 1번축의 2 ~ 4번에 해당하는 데이터를 출력 

#### [실습] arr의 1번축 값들의 합으로 표현된 배열 출력

In [90]:
arr = np.array([[1,2,3,4,5],
                [5,6,7,8,9],
                [9,1,2,3,4],
                [5,6,7,8,9],
               ])


### 4.2 DataFrame을 활용한 테이블형
**pandas**는 **DataFrame**이라는 형식을 활용해서 테이블형 데이터구조를 만들고 다양한 연산과 처리를 지원
- 테이블형 구조는 **row(행,관측지)** 과 **column(열,변수)** 로 표현되는 2차원 구조
- 데이터베이스(sql)이나 엑셀 형태와 비슷하여 많이 사용  

<img src="./data/20230827_155927.png"  width = 300 align="left"></img>  

#### DataFrame생성 과 특징
> DataFrame()객체 활용하여 생성, 테이블형 구조가 가능해야함

In [91]:
# 라이브러리 불러오기
import pandas as pd

In [92]:
# 딕셔너리를 활용한 DataFrame 생성
df = pd.DataFrame({'FIRST' : ['A', 'B', 'C', 'D'],
                   'SECOND': [7,6,5,8], 
                   'THIRD' : ['2023','2022','2021','2020']}) # freq='W-MON' : 매주 월요일
df

FIRST  SECOND THIRD
0     A       7  2023
1     B       6  2022
2     C       5  2021
3     D       8  2020

In [93]:
# 2차원 구조이면 생성 가능 
df = pd.DataFrame([['A',7,'2023'],
                   ['B',6,'2022'],
                   ['C',5,'2021'],
                   ['D',8,'2020']], 
                  columns = ['FIRST', 'SECOND', 'THIRD']) # freq='W-MON' : 매주 월요일
df

FIRST  SECOND THIRD
0     A       7  2023
1     B       6  2022
2     C       5  2021
3     D       8  2020

In [94]:
df = pd.DataFrame([{'FIRST':'A','SECOND':7,'THIRD': 2023},
                   {'FIRST':'B','SECOND':6,'THIRD': 2022},
                   {'FIRST':'C','SECOND':5,'THIRD': 2021},
                   {'FIRST':'D','SECOND':8,'THIRD': 2020}])
df

FIRST  SECOND  THIRD
0     A       7   2023
1     B       6   2022
2     C       5   2021
3     D       8   2020

#### DataFrame에서 시퀀스 연산 활용
> DataFrame에서 시퀀스 연산자[]는 해당 컬럼의 값들을 가져옵니다.  
>.loc[] 또는 .iloc[]를 통해 인덱스의 값들을 가져올 수 있습니다.

In [95]:
# []활용한 하나의 컬럼 가져오기
#     DataFrame에서 하나의 축만 가져오면 pandas의 Serise구조로 표현

df['SECOND']

0    7
1    6
2    5
3    8
Name: SECOND, dtype: int64

In [96]:
# .컬럼명 활용과 동일

df.SECOND

0    7
1    6
2    5
3    8
Name: SECOND, dtype: int64

In [97]:
# 리스트를 활용한 여러 컬럼 가져오기

df[['FIRST','THIRD']]

FIRST  THIRD
0     A   2023
1     B   2022
2     C   2021
3     D   2020

In [98]:
# DataFrame에 컬럼생성 및 일괄 추가
df['FOURTH'] = 10
df

FIRST  SECOND  THIRD  FOURTH
0     A       7   2023      10
1     B       6   2022      10
2     C       5   2021      10
3     D       8   2020      10

In [99]:
# DataFrame에 컬럼생성 및 일괄 추가
df['FOURTH'] = ['남자','여자','여자','남자']
df

FIRST  SECOND  THIRD FOURTH
0     A       7   2023     남자
1     B       6   2022     여자
2     C       5   2021     여자
3     D       8   2020     남자

In [100]:
# row 순서에 해당하는 데이터 또한 가져올 수 있음
df[1:3]

FIRST  SECOND  THIRD FOURTH
1     B       6   2022     여자
2     C       5   2021     여자

In [101]:
# 문자열 인덱스로 생성
df = pd.DataFrame([[7,'2023','남자'],
                   [6,'2022','여자'],
                   [5,'2021','여자'],
                   [8,'2020','남자']], 
                  index = ['A','B','C','D'],
                  columns = ['FIRST', 'SECOND', 'THIRD'])
df

FIRST SECOND THIRD
A      7   2023    남자
B      6   2022    여자
C      5   2021    여자
D      8   2020    남자

In [102]:
# loc[]를 활용한 하나의 로우 가져오기

df.loc['A']


FIRST        7
SECOND    2023
THIRD       남자
Name: A, dtype: object

In [103]:
# 리스트를 활용하여 여러 로우 가져오기
df.loc[['A','C']]

FIRST SECOND THIRD
A      7   2023    남자
C      5   2021    여자

In [104]:
# DataFrame에 row생성 및 일괄 추가 및 변경
df.loc['E'] = [9, 2019,'남자']
df.loc['A'] = [7, 2022, '여자']
df

FIRST SECOND THIRD
A      7   2022    여자
B      6   2022    여자
C      5   2021    여자
D      8   2020    남자
E      9   2019    남자

In [105]:
df.loc['B', 'SECOND']

'2022'

In [106]:
# iloc[]를 활용하여 순서로 로우 가져오기
df.iloc[0]

FIRST        7
SECOND    2022
THIRD       여자
Name: A, dtype: object

In [107]:
# :을 활용하여 여러 로우 가져오기
df.iloc[1:3]

FIRST SECOND THIRD
B      6   2022    여자
C      5   2021    여자

#### [실습] 다음 리스트형태의 데이터를 활용하여 컬럼이 score1, score2, score3, total 이고 인덱스가 4명의 이름인 DataFrame을 생성 
    total컬럼에는 현재 인덱스의 스코어 총합이 입력
<img src="./data/20230826_195021.png"  width = 240 align="left" ></img>

#### [실습] 결과 DataFrame에서 연진에 해당하는 점수들만 출력

In [108]:
import pandas as pd

n_list = ['동은','연진','여정','재준']
score1 = [76,62,64,62]
score2 = [56,74,51,44]
score3 = [81,35,74,63]


#### [심화] 다음 딕셔너리들을 활용하여 출력결과를 만드세요
    
    출력결과
<img src="./data/20230826_200046.png"  width = 160 align="left" ></img>

In [ ]:
import pandas as pd

users = {'123':'삼성',
         '124':'파이썬',
         '125':'데이터분석',}

products = {'a':['노트북', 200],
            'b':['자전거', 15],
            'c':['샴푸', 2],
            'd':['셔츠', 1],
            'e':['초코렛', 1]}

orders = [{'user_id':'123', 'products':['a','c']},
         {'user_id':'125', 'products':['e']},
         {'user_id':'124', 'products':['b','d','e']}]

#### End of script